### ISSUE TITLE
M3 Mac, TD crashes upon SceneLauncher import

### ISSUE THREAD

**Issue by foong** [DarienBrito/TDMorph#194] opened 2024-04-26 15:21 UTC
Hey Darien, working on a M3 mac Sonoma 14.3 and TD crashes every time SceneLauncher is imported.

**Comment by DarienBrito** [comment] 2024-05-06 11:49
Thanks for the report! This will be fixed in upcoming new version. Almost there... fixing some minor details and will upload. Stay tuned :)

**Comment by DarienBrito** [comment] 2024-05-19 11:46
Hi Foong, I believe the issue is solved now. Could you try with the lates version on this repository?

**Comment by foong** [comment] 2024-05-22 10:01
Okay, it's working now thanks! Will test out other features as well.

**Closed** 2024-06-04 11:45 UTC
