### ISSUE TITLE
Renamed Parameters don't persist across export/import

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#48] opened 2020-03-03 21:26 UTC
Finding a way to store the labels, both of the SlidersContainer and the parameters with the Json is gonna be important for making the export system usable in the long term. Maybe i brought this up with the first version, and maybe you're planning it for 2.0, but its gonna be really important for working with Indexed parameters

**Comment by DarienBrito** [comment] 2020-03-03 21:55
You mean you  want that the JSON stores the custom edited labels in addition to the real parameter labels?

**Comment by drmbt** [comment] 2020-03-03 23:07
How hard would it be to check if the label is different then the parameter name on create of a new parameter, and assume the label if a custom label already exists? Would save a lot of time in adapting to custom parameters that have already been relabeled.

**Comment by drmbt** [comment] 2020-03-03 23:51
Looks like the names of Slider Containers don't persist saves either, regardless of Json export

**Comment by DarienBrito** [comment] 2020-03-09 18:44
Custom labels are now properly stored and loaded. Please check in version 1.1.2

> 
> 
> How hard would it be to check if the label is different then the parameter name on create of a new parameter, and assume the label if a custom label already exists? Would save a lot of time in adapting to custom parameters that have already been relabeled.

This won't be supported. Labeling will be responsibility of the user, as it it will be quite a headache to manage proper parsing of data on the long run if doing this. The reason why the name of the parameter is taken and not labels is that labels can be equal, while paramnames by design cannot. So it is always safe to use that name internally.

**Closed by DarienBrito** 2020-03-09 18:44 UTC
Labels: bug

**Comment by drmbt** [comment] 2020-03-09 18:55
I don't mean to pass the label name to the paramname, just to pass it only to the label.
